import NavBar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import BackToTop from "@/components/shared/back-to-top";
import "./globals.css";

export const metadata = {
  title: "Tutor Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-lightwhite">
          <NavBar />
          <div className="container mx-auto">{children}</div>
          <Footer />
        </main>
        <BackToTop />
      </body>
    </html>
  );
}
